### ISSUE TITLE
Make use of fprettify

### ISSUE THREAD

**Issue by jryates** [optados-developers/optados#10]
https://github.com/pseewald/fprettify

**Comment by ajm143** [comment]
Code prettified with #43 requires @jryates to add back to the pre-commit hooks. I'm struggling to see how @jryates envisaged doing it as it doesn't look the same as Wannier90. (i.e. in Wannier90 it looks like a pre-commit workflow itself, however in OptaDOS it looks like it's designed to run at the same time as the test suite).

**Comment by jryates** [comment]
Maybe all is ok with #46

**Comment by ajm143** [comment]
I think this is done.
