### ISSUE TITLE
Links on website 

### ISSUE THREAD

**Issue by Rebecca-Nicholls** [optados-developers/optados#17]
- [Remove UCL links  ] 
- [Update people links on 'Links' page] 
- [Update publication  ]

**Comment by ajm143** [comment]
-[ ] Remove UCL links 
-[ ] Update people links on 'Links' page
-[ ] Update publications

**Comment by ajm143** [comment]
- [x] test

**Comment by ajm143** [comment]
- [ ] Remove UCL links

- [ ] Update people links on 'Links' page

- [ ]  Update publications somehow
