### ISSUE TITLE
process individual orbitals of pdos separately without merging 

### ISSUE THREAD

**Issue by zhubonan** [optados-developers/optados#26]
At the moment the PDOS routine sums the orbitals by species, sites or angular momentum channels. There is no option to turn this off and get projected dos for individual orbitals (i..e. by m numbers), I think. In some cases, having these channels are useful or essential, such as investigating the t2g/eg crystal field splitting of the d electrons in perovskites.

This can be achieve via bypassing subroutine `projection_merge`, and hence use the weights as it is. I took the liberty and modified code at: https://github.com/zhubonan/optados/tree/bonan_hacks. In my case I also let OptaDOS write out hdf5 files to avoid writing out a large number of formatted files. The latter may be more suitable for general use though.

**Comment by ajm143** [comment]
Dear Bonan, 

This is a good idea. We would be pleased to receive a pull request with your modifications.

I suggest that you add an option to the pdos keyword : all ?

Best wishes,
Andrew

**Comment by ajm143** [comment]
@zhubonan Would you like to send us a PR on this ?

**Comment by zhubonan** [comment]
Sorry,I should have replied to this earlier. I probably won't be able to send in a PR as I have not worked on it since and it would take a while to pick it up. I don't think the changes I made involvign HDF5 is a good way to do this either...
