### ISSUE TITLE
OptaDOS should respond to --version

### ISSUE THREAD

**Issue by ajm143** [optados-developers/optados#27]
In a similar way to how CASTEP does it.

**Comment by ajm143** [comment]
Write a bash script to scrape git log. 
Use it to make a buildinfo.f90, which contains a user defined type.
Edit optados.f90 under the "help" catcher line -- call a subroutine at the bottom of the file.

**Comment by ml-evs** [comment]
`git describe --tags` gives you `<last tag>-<number of commits since last tag>-<last commit hash in short form>`, if that's helpful.

**Comment by ajm143** [comment]
Note to self (+world+dog) Can't do this until I have tagged the previous releases, see #20. Otherwise what @ml-evs said.

**Comment by ajm143** [comment]
Solved by PR #45.
