### ISSUE TITLE
Hardcoded paths left in test suite

### ISSUE THREAD

**Issue by ml-evs** [optados-developers/optados#30]
Just randomly noticed this, guess you want to fix it...

https://github.com/optados-developers/optados/blob/974eaa31c5524574317d6207256961cac00728b5/optados/tools/od2od_tester.sh#L7-L8

**Comment by ajm143** [comment]
Good spot. It's only a temporary tester whilst we get the real test suite up and running. But I'll fix it after I've got the most recent pull request done.

A.

**Comment by ajm143** [comment]
Solved by #45
