### ISSUE TITLE
Help Regarding Projected Bandstructure

### ISSUE THREAD

**Issue by sajidurehman** [optados-developers/optados#32]
Hi Developers,
                 I am new to optados. Using optados we can easily get the PDOS data from .pdos.dat file and can be draw with any plotting package. But, I am little bit confuse about PDIS data (which is available in .pdis.dat file) and its drawing. How can I draw any/combind projector bandstructure in any plotting package? Thank you in andvance

Best Wishes
Sajid

**Comment by ajm143** [comment]
Dear Sajid, 

Currently the best way to lot a PDIS is to use the Matador plotting routines. See:

https://docs.matador.science/en/stable/notebooks/projected_spectral.html?highlight=PDIS

Please use the Optados mailing list for help using OptaDOS (OPTADOS@JISCMAIL.AC.UK). This section is for bug reports.

Many thanks,
Andrew

**Comment by sajidurehman** [comment]
Thank you for reply and matador link.
