### ISSUE TITLE
OptaDOS and Hybrid Functional Calculation

### ISSUE THREAD

**Issue by sajidurehman** [optados-developers/optados#36]
Hi Developers, 
                      I am trying to use the OptaDOS for hybrid functional calculation. I come to know CASTEP does not produce the .dome_bin file when running with hybrid functionals. OptaDOS needs this file for many of its tasks. Then, how could we calculate the electronic band structure and DOS using OptaDOS with CASTEP. Looking forward to yours kind response. 

Best Wishes
Sajid

**Comment by ajm143** [comment]
You can get around this by using fixed smearing, you do not need a .dome_bin file for this.

As this isn't a bug, I'm going to close the ticket. Please use the mailing list in the future.

Andrew.

**Comment by sajidurehman** [comment]
Thank you for your kind response. Now after using fixed smearing problem is solved for pdos. Unfortunately, got another problem when trying calculate the pdispersion. Following is the error. 

corrupted size vs. prev_size

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f38e6f8632a
#1  0x7f38e6f85503
#2  0x7f38e681afcf
#3  0x7f38e681af47
#4  0x7f38e681c8b0
#5  0x7f38e6865906
#6  0x7f38e686c979
#7  0x7f38e68741ce
#8  0x7f38e7103995
#9  0x7f38e7102be3
#10  0x563b53e4b1a2
#11  0x563b53e7d3b5
#12  0x563b53e2af04
#13  0x563b53e29c28
#14  0x7f38e67fdb96
#15  0x563b53e29c59
#16  0xffffffffffffffff
Aborted (core dumped)

I used the following tag in Si.odi for pdispersion 
pdispersion: species
fixed_smearing: 0.02
set_efermi_zero: True
dos_per_volume: True
broadening: fixed
dos_spacing: 0.01
task: pdispersion

Please help me to resolve this issue. Again looking forward to your kind response. 

Best Wishes
Sajid
