### ISSUE TITLE
Missing d-channel in f-block elements ?

### ISSUE THREAD

**Issue by ajm143** [optados-developers/optados#41]
Note
Element - Channels that OptaDOS shows - Electronic Config 
Xe [Kr] 4d^10 5s^2 5p^6
**Mo** - s p d - [Kr] 4d^5 5s^1 pdos_mwab%norbitals=26
**Ba**  - s p d -  [Xe] 6s^2  pdos_mwab%norbitals=20
**Eu**  - s p d f  - [Xe]  4f^7 5d^0 6s^2 
**Gd**  - s p d f  - [Xe]  4f^7 5d^1 6s^2 
**W**   - s p f - [Xe]  4f^14 5d^4 6s^2  iprint=3 ==> s,p,f. pdos_mwab%norbitals=22
**Re**  - s p f  - [Xe]  4f^14 5d^5 6s^2 
**Os**  - s p f  - [Xe]  4f^14 5d^6 6s^2 
**Pt**   - s p f  - [Xe]  4f^14 5d^10 6s^0 
**Pb** - s p d - [Xe] 4f^14 5d^10 6s^2 6p^2 pdos_mwab%norbitals=56

https://en.wikipedia.org/wiki/Group_(periodic_table)#/media/File:Simple_Periodic_Table_Chart-blocks.svg

**Comment by ajm143** [comment]
-----Original Message-----
From: Jonathan Yates 
To: Rebecca Nicholls 
Subject: Re: OptaDOS update

Ok, I’ll do a bit of digging and see where there are getting lost.

Jonathan

On 16 Dec 2021, at 21:33, Rebecca Nicholls 


Hi Jonathan 

For the calculations I did:

```
Pt: 
   Atomic Populations (Mulliken)
   -----------------------------
 Species          Ion     s      p      d      f     Total  Charge (e) 
 =====================================================================
  Pt              1     3.01   6.00   8.99  14.00  32.00     0.00 
 Pt              2     3.01   6.00   8.99  14.00  32.00     0.00
 Pt              3     3.01   6.00   8.99  14.00  32.00     0.00
 Pt              4     3.01   6.00   8.99  14.00  32.00     0.00
=====================================================================

```
So I guess I've used more than three states in the basis - how do I check?

```
For W:
Atomic Populations (Mulliken)
   -----------------------------
Species          Ion     s      p      d      f     Total  Charge (e)
=====================================================================
W               1     2.94   6.00   5.06  14.00  28.00     0.00
W               2     2.94   6.00   5.06  14.00  28.00     0.00
=====================================================================
(4d[10]) 5s[2] 5p[6] 6s[2] 4f[14] 5d[4] 6p[0] so I think 28 makes sense.  

```
The castep muliken populations appear to be showing something sensible, but the states don't all appear in the pdos in optados. 

Best wishes
Rebecca


-----Original Message-----
From: Jonathan Yates 
To: Rebecca Nicholls 

Is this an issue with semi-core states and the LCAO basis. I’ve put some notes below.
If this is the problem - then it is CASTEP and not optados. CASTEP just needs to choose better defaults (it is only my long term list for improvements to OTFG).
If the issue is something else, let me know and I’ll look further.

Jonathan

The issue is how castep determines which orbitals to use to build the LCAO basis to do the projection. I think that with semi-core state CASTEP makes a mistake with the default value. By default SPECIES_LCAO_STATES is set to 3. The population analysis says
  ```
 Atomic Populations (Mulliken)
  -----------------------------
Species   Ion     s      p      d      f     Total  Charge (e)
==============================================================
Pt       1     2.00   6.00   0.00  14.00  22.00    10.00
==============================================================

```
So we are missing 10 electrons. No ‘d’ states - and the s and p are fully occupied. Looking at the valence states we have

5s[2] 5p[6] 4f[14] 6s[1] 4d[9] 6p[0]

So if we only have 3 states in the basis we miss the 4d and the 6s/p states. But if we set

```
%BLOCK SPECIES_LCAO_STATES
   Pt         6
%ENDBLOCK SPECIES_LCAO_STATES

```
then

 ```
 Atomic Populations (Mulliken)
  -----------------------------
Species   Ion     s      p      d      f     Total  Charge (e)
==============================================================
Pt       1     2.64   6.70   8.67  14.00  32.00     0.00
==============================================================

```
Which looks more reasonable.

**Comment by jryates** [comment]
I'm struggling to reproduce this error. In my simple cases I seem to have all the right states. Is there a simple set of inputs that shows the problem.

**Comment by Rebecca-Nicholls** [comment]
Hi @jryates, here are the .cell and .param files for the Pt calculation above along with the .castep, .odo and .pdos.dat.  The castep calculation uses academic release version 20.11, let me know if anything else would be useful.
[Pt flies.zip](https://github.com/optados-developers/optados/files/8442960/Pt.flies.zip)

**Comment by jryates** [comment]
If I run with the latest castep and latest optados, then I get all of the spin channels. So no issue.
Your calculation is run with optados 1.2 (not 1.3). Can you try with the current optados. I don't think the issue will be the castep version (as the LCAO basis is the same, and I haven't changed the code that writes out the weights)

**Comment by Rebecca-Nicholls** [comment]
Hi @jryates Unfortunately trying the latest optados (1.3 not 1.2) still has the same problem.

**Comment by Rebecca-Nicholls** [comment]
Currently compiling castep21.11 and will try with that and optados 1.3.

**Comment by jryates** [comment]
If that still fails, send me your odi file - as that is the only part of the workflow that might be different

**Comment by Rebecca-Nicholls** [comment]
Hi @jryates It works with castep21.11 - I checked castep19 and castep18 and they both had the d-states missing, not sure why 21.11 works but good that it does!

**Comment by jryates** [comment]
Good - I'll mark this as closed.
