### ISSUE TITLE
how to know the birefringence of a biaxial crystal

### ISSUE THREAD

**Issue by qingtianya-wyt** [optados-developers/optados#50]
Hi,
I am using the optados to calculate the optical properties,such as the refractive index.I have obtained the components of dielectric function (ɛxx,ɛyy,ɛzz) by set this tag (OPTICS_GEOM        : tensor).In order to calculate the birefringence, I need to know the value of nx,ny,nz. For an uniaxial crystal, its birefringence equals to the value of  （nx-nz） which could write as (ɛxx -ɛzz). For a biaxial crystal， may I obtain the birefringence by max{ɛi} - min{ɛi} or how could I get its birefringence correctly  by dielectric function?

**Comment by qingtianya-wyt** [comment]
I made a mistake. For an uniaxial crystal, it should be nx-ny=sqrt(ɛxx)-sqrt(ɛzz));for a biaxial crystal,maybe its birefringence equals to max(sqrt(ɛi)) - min(sqrt(i)) ?

**Comment by jryates** [comment]
As you note, the three refractive indexes are the square roots of the principal components of the dielectric tensor.
According to Hecht's Optics "The birefringence of biaxial crystals is measured as the numerical difference between the largest and smallest of these indices."
